module.exports ={
    "success": true,
    "count": 0,
    "data": [
        {
            "name": "Obrol Seharian ke Semua Operator",
            "amount": "3,448",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "720",
            "type": "VOUCHER INJECTION",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Obrol Seharian ke Semua Operator",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 1GB,5rb/2hr SUM (VOU)",
            "amount": "4,925",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "582",
            "type": "VOUCHER INJECTION",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 1GB , Masa Aktif 2 hari ",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 5K",
            "amount": "5,750",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "721",
            "type": "VOUCHER INJECTION",
            "subtype": "Reload",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "5000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom SMS/30hr",
            "amount": "5,910",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "698",
            "type": "VOUCHER INJECTION",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Freedom SMS/30hr",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 2,5GB/5 Hari Sumatera",
            "amount": "10,700",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "571",
            "type": "VOUCHER INJECTION",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 2.5GB , Masa Aktif 5 hari ",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 10K",
            "amount": "10,750",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "722",
            "type": "VOUCHER INJECTION",
            "subtype": "Reload",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "10000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "SMS Ke Semua 30Hr",
            "amount": "11,640",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "699",
            "type": "VOUCHER INJECTION",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "SMS Ke Semua 30Hr",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Unlimited Onnet + 30 min Offnet,7D",
            "amount": "12,610",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "697",
            "type": "VOUCHER INJECTION",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Unlimited Onnet + 30 min Offnet,7D",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 5GB,15rb/5hr SUM (VOU)",
            "amount": "14,500",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "591",
            "type": "VOUCHER INJECTION",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 5GB , Masa Aktif 5 hari ",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 3GB/30hr (Sumbagsel)  ZONA2",
            "amount": "16,900",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "542",
            "type": "VOUCHER INJECTION",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "KUOTA UTAMA 3GB, Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri  Dapatkan tambahan kuota zona 2GB jika diaktifkan di wilayah Zona 2 area Sumabagsel",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 7GB,20rb/7hr SUM (VOU)",
            "amount": "19,300",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "586",
            "type": "VOUCHER INJECTION",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 7GB , Masa Aktif 7 hari ",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 15GB,3hr SUM",
            "amount": "24,200",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "576",
            "type": "VOUCHER INJECTION",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Freedom Internet 15GB,3hr",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Unlimited Onnet + 60 min Offnet",
            "amount": "24,250",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "701",
            "type": "VOUCHER INJECTION",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Unlimited Onnet + 60 min Offnet",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 25K",
            "amount": "25,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "723",
            "type": "VOUCHER INJECTION",
            "subtype": "Reload",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "25000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 5.5GB/30hr (Sumbagsel)  ZONA2",
            "amount": "27,600",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "506",
            "type": "VOUCHER INJECTION",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "KUOTA UTAMA 5.5GB, Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri  Dapatkan tambahan kuota zona 3.5GB jika diaktifkan di wilayah Zona 2 area Sumabagsel",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Combo 6GB 30hr",
            "amount": "30,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "220",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom Combo",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 4GB+Kuota Malam 2GB. Nelpon Ke Sesama IM3 & Tri Sepuasnya (5,000 Menit) + Nelp operator lain 5 Menit. PULSA SAFE. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 5.5GB 30hr",
            "amount": "30,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "678",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 1GB + 4.5GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 9GB 30HR  ZONA2  ",
            "amount": "38,400",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "512",
            "type": "VOUCHER INJECTION",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 9GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 6GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Combo 10GB 30hr (Sumbagsel)",
            "amount": "40,400",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "225",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom Combo",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 7GB+Kuota Malam 3GB. Nelpon Ke Sesama IM3 & Tri Sepuasnya (5,000 Menit) + Nelp operator lain 10 Menit. PULSA SAFE. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Unlimited Onnet + 250 min Offnet",
            "amount": "48,250",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "700",
            "type": "VOUCHER INJECTION",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Unlimited Onnet + 250 min Offnet",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 50K",
            "amount": "49,500",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "724",
            "type": "VOUCHER INJECTION",
            "subtype": "Reload",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "50000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 10GB 30hr",
            "amount": "50,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "748",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 2GB + 8GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 16GB 30HR  ZONA2  ",
            "amount": "59,300",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "515",
            "type": "VOUCHER INJECTION",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 16GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 14GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Combo 20GB 30hr",
            "amount": "61,200",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "223",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom Combo",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 15GB+Kuota Malam 5GB. Nelpon Ke Sesama IM3 & Tri Sepuasnya (5,000 Menit) + Nelp operator lain 20 Menit. PULSA SAFE. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 20GB 30hr (Sumbagsel)",
            "amount": "70,700",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "756",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 3GB + 17GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 25GB 30HR  ZONA2  ",
            "amount": "80,300",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "518",
            "type": "VOUCHER INJECTION",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 25GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 20GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Combo 30GB 30hr",
            "amount": "82,200",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "222",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom Combo",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 23GB+Kuota Malam 7GB. Nelpon Ke Sesama IM3 & Tri Sepuasnya (5,000 Menit) + Nelp operator lain 20 Menit. PULSA SAFE. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 35GB 30hr",
            "amount": "91,700",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "758",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 7GB + 28GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 42GB 30HR  ZONA2  ",
            "amount": "101,300",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "548",
            "type": "VOUCHER INJECTION",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 42GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 28GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 45GB 30hr",
            "amount": "102,200",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "759",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 10GB + 35GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U Jumbo 30hr",
            "amount": "155,520",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "760",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 90GB + Nelpon&SMS Puas ke Sesama IM3 dan Tri. 100 Menit & 100SMS ke Opr lain. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        }
    ]
}
