module.exports ={
    "success": true,
    "count": 0,
    "data": [
        {
            "name": "Denom 5K",
            "amount": "5,750",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "206",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "5000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 10K",
            "amount": "10,750",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "213",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "10000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 15K",
            "amount": "15,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "211",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "15000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 20K",
            "amount": "20,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "217",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "20000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 25K",
            "amount": "25,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "218",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "1",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "25000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 30K",
            "amount": "29,850",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "209",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "30000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 40K",
            "amount": "39,800",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "207",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "40000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 50K",
            "amount": "49,500",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "219",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "1",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "50000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 60K",
            "amount": "59,400",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "212",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "60000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 80K",
            "amount": "78,800",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "208",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "80000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 100K",
            "amount": "98,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "210",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "100000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 125K",
            "amount": "125,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "205",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "125000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 150K",
            "amount": "150,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "204",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "150000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 200K",
            "amount": "200,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "203",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "200000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 300K",
            "amount": "286,500",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "215",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "300000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 400K",
            "amount": "378,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "216",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "400000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 500K",
            "amount": "470,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "214",
            "type": "RELOAD",
            "subtype": "Regular",
            "frpkg": "0",
            "typeid": "1",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "500000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
    ]
}
