module.exports ={
    "success": true,
    "count": 0,
    "data": [
        {
            "name": "Obrol Seharian ke Semua Operator",
            "amount": "3,448",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "137",
            "type": "DATA PACKAGE",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Obrol Seharian ke Semua Operator",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 1GB,5rb/2hr SUM",
            "amount": "4,925",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "106",
            "type": "DATA PACKAGE",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 1GB , Masa Aktif 2 hari ",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom SMS/30hr",
            "amount": "5,910",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "136",
            "type": "DATA PACKAGE",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Freedom SMS/30hr",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "OBROL UL 30HR",
            "amount": "9,600",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "142",
            "type": "DATA PACKAGE",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Obrol Unlimited ke sesama IM3 Ooredoo dan Tri, Masa Aktif 30 hari",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 2,5GB/5 Hari Sumatera",
            "amount": "10,600",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "96",
            "type": "DATA PACKAGE",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 2.5GB , Masa Aktif 5 hari ",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "SMS Ke Semua 30Hr",
            "amount": "11,520",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "138",
            "type": "DATA PACKAGE",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "SMS Ke Semua 30Hr",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Unlimited Onnet + 30 min Offnet,7D",
            "amount": "12,500",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "135",
            "type": "DATA PACKAGE",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Unlimited Onnet + 30 min Offnet,7D",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 5GB,15rb/5hr SUM",
            "amount": "14,400",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "121",
            "type": "DATA PACKAGE",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 5GB , Masa Aktif 5 hari ",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 3GB 30HR ZONA2",
            "amount": "16,800",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "80",
            "type": "DATA PACKAGE",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 3GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 2GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 7GB,20rb/7hr SUM",
            "amount": "19,100",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "116",
            "type": "DATA PACKAGE",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 7GB , Masa Aktif 7 hari ",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 15GB,3hr SUM",
            "amount": "23,900",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "97",
            "type": "DATA PACKAGE",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Freedom Internet 15GB,3hr",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Unlimited Onnet + 60 min Offnet",
            "amount": "24,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "140",
            "type": "DATA PACKAGE",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Unlimited Onnet + 60 min Offnet",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 5.5GB 30HR  ZONA2 ",
            "amount": "27,300",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "84",
            "type": "DATA PACKAGE",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 5.5GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 3.5GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Combo 6GB 30hr",
            "amount": "29,700",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "1",
            "type": "DATA PACKAGE",
            "subtype": "Freedom Combo",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 4GB+Kuota Malam 2GB. Nelpon Ke Sesama IM3 & Tri Sepuasnya (5,000 Menit) + Nelp operator lain 5 Menit. PULSA SAFE. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 5.5GB 30hr",
            "amount": "29,700",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "125",
            "type": "DATA PACKAGE",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 1GB + 4.5GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 9GB 30HR  ZONA2 ",
            "amount": "37,800",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "87",
            "type": "DATA PACKAGE",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 9GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 6GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Combo 10GB 30hr",
            "amount": "39,700",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "5",
            "type": "DATA PACKAGE",
            "subtype": "Freedom Combo",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 7GB+Kuota Malam 3GB. Nelpon Ke Sesama IM3 & Tri Sepuasnya (5,000 Menit) + Nelp operator lain 10 Menit. PULSA SAFE. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Unlimited Onnet + 250 min Offnet",
            "amount": "47,300",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "139",
            "type": "DATA PACKAGE",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Unlimited Onnet + 250 min Offnet",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 10GB 30hr",
            "amount": "49,200",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "132",
            "type": "DATA PACKAGE",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 2GB + 8GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 16GB 30HR  ZONA2 ",
            "amount": "58,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "59",
            "type": "DATA PACKAGE",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 16GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 14GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Combo 20GB 30hr",
            "amount": "59,900",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "4",
            "type": "DATA PACKAGE",
            "subtype": "Freedom Combo",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 15GB+Kuota Malam 5GB. Nelpon Ke Sesama IM3 & Tri Sepuasnya (5,000 Menit) + Nelp operator lain 20 Menit. PULSA SAFE. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 20GB 30hr",
            "amount": "69,200",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "131",
            "type": "DATA PACKAGE",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 3GB + 17GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Travel on 5GB 14Days",
            "amount": "75,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "476",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet 5GB, Voice PPU Rp1/dtk di 5 menit pertama, lalu Rp 25/dtk hingga 23:59 kesemua Operator Domestik dan ke 39 negara menggunakan 001/008 berlaku 14 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 25GB 30HR  ZONA2 ",
            "amount": "78,600",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "158",
            "type": "DATA PACKAGE",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 25GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 20GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Combo 30GB 30hr",
            "amount": "80,500",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "3",
            "type": "DATA PACKAGE",
            "subtype": "Freedom Combo",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 23GB+Kuota Malam 7GB. Nelpon Ke Sesama IM3 & Tri Sepuasnya (5,000 Menit) + Nelp operator lain 20 Menit. PULSA SAFE. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 35GB 30hr",
            "amount": "89,800",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "130",
            "type": "DATA PACKAGE",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 7GB + 28GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 42GB 30HR  ZONA2 ",
            "amount": "99,200",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "82",
            "type": "DATA PACKAGE",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 42GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 28GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Roam Kuota 1GB Asia Australia 3 Hari",
            "amount": "100,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "188",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Roaming Kuota 1 GB, 3 Hari, di 19 Negara Asia Australia",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Roam Malaysia 100GB 7Hari",
            "amount": "100,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "483",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet Kuota 100GB Berlaku 7 hari. Berlaku di seluruh Operator di malaysia (DIGI sebagai Operator Utama)",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Roam Singapura 100GB 7Hari",
            "amount": "100,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "187",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet Kuota 100GB Berlaku 7 hari. Berlaku di seluruh Operator di Singapura (Starhub sebagai Operator Utama)",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 45GB 30hr",
            "amount": "100,100",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "129",
            "type": "DATA PACKAGE",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 10GB + 35GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Travel on 20GB 30Days",
            "amount": "110,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "477",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet 20GB, Voice PPU Rp1/dtk di 5 menit pertama, lalu Rp 25/dtk hingga 23:59 kesemua Operator Domestik dan ke 39 negara menggunakan 001/008 berlaku 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET SENSASI 50GB 30hr",
            "amount": "112,200",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "160",
            "type": "DATA PACKAGE",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Freedom Internet 50GB/30hr",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet Sensasi 100GB",
            "amount": "140,300",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "164",
            "type": "DATA PACKAGE",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Freedom Internet 100GB/30hr",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U Jumbo 30hr",
            "amount": "151,500",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "128",
            "type": "DATA PACKAGE",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Akses Internet 90GB ,Nelpon&SMS Sepuasnya ke IM3 dan Tri.100 Menit Nelpon&100 SMS ke Operator Lain ,Masa Aktif 30 hari",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Roam Kuota 2.5GB Asia Australia 7 Hari",
            "amount": "200,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "489",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Roaming Kuota 2.5 GB, 7 Hari, di 19 Negara Asia Australia",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Umroh Haji Internet 10 Hari",
            "amount": "245,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "486",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet 5GB berlaku 10 hari. Berlaku di Arab Saudi, Palestina, Mesir, Qatar, Turki, UAE, Jordan",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Umroh Haji Combo 10 Hari",
            "amount": "325,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "479",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet 5GB, 60 Menit Nelpon dan Terima Panggilan, 60 SMS ke semua Operator berlaku 10 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Umroh Haji Internet 15 Hari",
            "amount": "325,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "478",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet 9GB berlaku 15 hari. Berlaku di Arab Saudi, Palestina, Mesir, Qatar, Turki, UAE, Jordan",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Umroh Haji Internet 20 Hari",
            "amount": "350,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "487",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet 10GB berlaku 20 hari. Berlaku di Arab Saudi, Palestina, Mesir, Qatar, Turki, UAE, Jordan.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Roam Kuota 2GB Amerika Eropa Afrika 7 Hari",
            "amount": "400,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "482",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Roaming Kuota 2 GB, 7 Hari, di 56 Negara Amerika, Eropa, Asia, Australia",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Umroh Haji Combo 15 Hari",
            "amount": "450,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "488",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet 9GB, 75 Menit Nelpon dan Terima Panggilan, 75 SMS ke semua Operator berlaku 15 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Umroh Haji Combo 20 Hari",
            "amount": "500,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "480",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet 10GB, 90 Menit Nelpon dan Terima Panggilan,90 SMS ke semua Operator berlaku 20 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Umroh Haji Internet 30 Hari",
            "amount": "500,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "484",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet 15GB berlaku 30 hari. Berlaku di Arab Saudi, Palestina, Mesir, Qatar, Turki, UAE, Jordan",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Umroh Haji Combo 30 Hari",
            "amount": "600,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "189",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet 15GB, 100 Menit Nelpon dan Terima Panggilan,100 SMS ke semua Operator berlaku 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Umroh Haji Internet 45 Hari",
            "amount": "650,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "485",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet 20GB berlaku 45 hari. Berlaku di Arab Saudi, Palestina, Mesir, Qatar, Turki, UAE, Jordan",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Umroh Haji Combo 45 Hari",
            "amount": "750,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "190",
            "type": "DATA PACKAGE",
            "subtype": "Roaming",
            "frpkg": "0",
            "typeid": "2",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Internet 20GB, 120 Menit Nelpon dan Terima Panggilan,120 SMS ke semua Operator berlaku 45 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Obrol Seharian ke Semua Operator",
            "amount": "3,448",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "720",
            "type": "VOUCHER INJECTION",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Obrol Seharian ke Semua Operator",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 1GB,5rb/2hr SUM (VOU)",
            "amount": "4,925",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "582",
            "type": "VOUCHER INJECTION",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 1GB , Masa Aktif 2 hari ",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 5K",
            "amount": "5,750",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "721",
            "type": "VOUCHER INJECTION",
            "subtype": "Reload",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "5000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom SMS/30hr",
            "amount": "5,910",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "698",
            "type": "VOUCHER INJECTION",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Freedom SMS/30hr",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 2,5GB/5 Hari Sumatera",
            "amount": "10,700",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "571",
            "type": "VOUCHER INJECTION",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 2.5GB , Masa Aktif 5 hari ",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 10K",
            "amount": "10,750",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "722",
            "type": "VOUCHER INJECTION",
            "subtype": "Reload",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "10000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "SMS Ke Semua 30Hr",
            "amount": "11,640",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "699",
            "type": "VOUCHER INJECTION",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "SMS Ke Semua 30Hr",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Unlimited Onnet + 30 min Offnet,7D",
            "amount": "12,610",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "697",
            "type": "VOUCHER INJECTION",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Unlimited Onnet + 30 min Offnet,7D",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 5GB,15rb/5hr SUM (VOU)",
            "amount": "14,500",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "591",
            "type": "VOUCHER INJECTION",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 5GB , Masa Aktif 5 hari ",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 3GB/30hr (Sumbagsel)  ZONA2",
            "amount": "16,900",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "542",
            "type": "VOUCHER INJECTION",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "KUOTA UTAMA 3GB, Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri  Dapatkan tambahan kuota zona 2GB jika diaktifkan di wilayah Zona 2 area Sumabagsel",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 7GB,20rb/7hr SUM (VOU)",
            "amount": "19,300",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "586",
            "type": "VOUCHER INJECTION",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 7GB , Masa Aktif 7 hari ",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 15GB,3hr SUM",
            "amount": "24,200",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "576",
            "type": "VOUCHER INJECTION",
            "subtype": "Harian",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Freedom Internet 15GB,3hr",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Unlimited Onnet + 60 min Offnet",
            "amount": "24,250",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "701",
            "type": "VOUCHER INJECTION",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Unlimited Onnet + 60 min Offnet",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 25K",
            "amount": "25,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "723",
            "type": "VOUCHER INJECTION",
            "subtype": "Reload",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "25000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Internet 5.5GB/30hr (Sumbagsel)  ZONA2",
            "amount": "27,600",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "506",
            "type": "VOUCHER INJECTION",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "KUOTA UTAMA 5.5GB, Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri  Dapatkan tambahan kuota zona 3.5GB jika diaktifkan di wilayah Zona 2 area Sumabagsel",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Combo 6GB 30hr",
            "amount": "30,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "220",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom Combo",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 4GB+Kuota Malam 2GB. Nelpon Ke Sesama IM3 & Tri Sepuasnya (5,000 Menit) + Nelp operator lain 5 Menit. PULSA SAFE. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 5.5GB 30hr",
            "amount": "30,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "678",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 1GB + 4.5GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 9GB 30HR  ZONA2  ",
            "amount": "38,400",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "512",
            "type": "VOUCHER INJECTION",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 9GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 6GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Combo 10GB 30hr (Sumbagsel)",
            "amount": "40,400",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "225",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom Combo",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 7GB+Kuota Malam 3GB. Nelpon Ke Sesama IM3 & Tri Sepuasnya (5,000 Menit) + Nelp operator lain 10 Menit. PULSA SAFE. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Unlimited Onnet + 250 min Offnet",
            "amount": "48,250",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "700",
            "type": "VOUCHER INJECTION",
            "subtype": "Paket Lainnya",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Unlimited Onnet + 250 min Offnet",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Denom 50K",
            "amount": "49,500",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "724",
            "type": "VOUCHER INJECTION",
            "subtype": "Reload",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "50000",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 10GB 30hr",
            "amount": "50,000",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "748",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 2GB + 8GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 16GB 30HR  ZONA2  ",
            "amount": "59,300",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "515",
            "type": "VOUCHER INJECTION",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 16GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 14GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Combo 20GB 30hr",
            "amount": "61,200",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "223",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom Combo",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 15GB+Kuota Malam 5GB. Nelpon Ke Sesama IM3 & Tri Sepuasnya (5,000 Menit) + Nelp operator lain 20 Menit. PULSA SAFE. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 20GB 30hr (Sumbagsel)",
            "amount": "70,700",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "756",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 3GB + 17GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 25GB 30HR  ZONA2  ",
            "amount": "80,300",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "518",
            "type": "VOUCHER INJECTION",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 25GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 20GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom Combo 30GB 30hr",
            "amount": "82,200",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "222",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom Combo",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 23GB+Kuota Malam 7GB. Nelpon Ke Sesama IM3 & Tri Sepuasnya (5,000 Menit) + Nelp operator lain 20 Menit. PULSA SAFE. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 35GB 30hr",
            "amount": "91,700",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "758",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 7GB + 28GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "FREEDOM INTERNET 42GB 30HR  ZONA2  ",
            "amount": "101,300",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "548",
            "type": "VOUCHER INJECTION",
            "subtype": "30 hari",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 42GB , Masa Aktif 30 hari, Pulsa Safe, Nelp Sepuasnya ke IM3 dan Tri. Dapatkan tambahan kuota zona 28GB jika diaktifkan di wilayah Zona 2",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U 45GB 30hr",
            "amount": "102,200",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "759",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 10GB + 35GB Kuota Youtube, Netflix, Instagram, Zoom & Apps. Nelpon sepuasnya ke IM3 dan Tri. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        },
        {
            "name": "Freedom U Jumbo 30hr",
            "amount": "155,520",
            "discntamount": null,
            "discntamountnew": null,
            "recomprice": null,
            "dnmcode": "760",
            "type": "VOUCHER INJECTION",
            "subtype": "Freedom U",
            "frpkg": "0",
            "typeid": "3",
            "issplpkg": "0",
            "strikeout": 0,
            "detail_benefit": "Kuota Utama 90GB + Nelpon&SMS Puas ke Sesama IM3 dan Tri. 100 Menit & 100SMS ke Opr lain. Pulsa Safe. Masa aktif 30 hari.",
            "disclaimer": "Price before discount.",
            "desc": null,
            "reload_amount": null,
            "shortdesc": null
        }
    ]
}
